// Logic for Robots.txt Generator

document.addEventListener('DOMContentLoaded', () => {
    const defaultAccessSelect = document.getElementById('default-access');
    const sitemapInput = document.getElementById('sitemap-url');
    const rulesContainer = document.getElementById('rules-container');
    const addRuleBtn = document.getElementById('add-rule-btn');
    const generateBtn = document.getElementById('generate-btn');
    const clearBtn = document.getElementById('clear-btn');
    const copyBtn = document.getElementById('copy-btn');
    const downloadBtn = document.getElementById('download-btn');
    const outputCode = document.getElementById('robot-code-output');

    // Popular bots for dropdown
    const BOTS = [
        { val: '*', label: '* (All Bots)' },
        { val: 'Googlebot', label: 'Googlebot (Google)' },
        { val: 'Googlebot-Image', label: 'Googlebot-Image' },
        { val: 'Bingbot', label: 'Bingbot (Bing)' },
        { val: 'Slurp', label: 'Slurp (Yahoo)' },
        { val: 'DuckDuckBot', label: 'DuckDuckBot' },
        { val: 'Baiduspider', label: 'Baiduspider (Baidu)' },
        { val: 'YandexBot', label: 'YandexBot' },
        { val: 'Applebot', label: 'Applebot' }
    ];

    function createRuleRow() {
        const row = document.createElement('div');
        row.className = 'rule-row';

        // Bot Select
        const botSelect = document.createElement('select');
        botSelect.className = 'select-input';
        BOTS.forEach(bot => {
            const opt = document.createElement('option');
            opt.value = bot.val;
            opt.textContent = bot.label;
            botSelect.appendChild(opt);
        });

        // Action Select
        const actionSelect = document.createElement('select');
        actionSelect.className = 'select-input';
        actionSelect.innerHTML = `
            <option value="Disallow">Disallow</option>
            <option value="Allow">Allow</option>
        `;

        // Path Input
        const pathInput = document.createElement('input');
        pathInput.type = 'text';
        pathInput.className = 'w-full';
        pathInput.placeholder = 'e.g. /admin/ or /private.html';

        // Remove Button
        const removeBtn = document.createElement('button');
        removeBtn.className = 'btn-remove';
        removeBtn.innerHTML = '×';
        removeBtn.title = 'Remove Rule';
        removeBtn.onclick = () => {
            row.remove();
            generateRobotsTxt();
        };

        row.appendChild(botSelect);
        row.appendChild(actionSelect);
        row.appendChild(pathInput);
        row.appendChild(removeBtn);

        // Auto-generate on input changes
        botSelect.addEventListener('change', generateRobotsTxt);
        actionSelect.addEventListener('change', generateRobotsTxt);
        pathInput.addEventListener('input', generateRobotsTxt);

        return row;
    }

    addRuleBtn.addEventListener('click', () => {
        rulesContainer.appendChild(createRuleRow());
    });

    function generateRobotsTxt() {
        let txt = '';

        // 1. Default Access
        const defaultAccess = defaultAccessSelect.value;
        txt += `User-agent: *\n`;
        if (defaultAccess === 'allow') {
            txt += `Disallow:\n`;
        } else {
            txt += `Disallow: /\n`;
        }
        txt += `\n`;

        // 2. Custom Rules
        // Group rules by User-agent to keep it clean
        const customRules = {};
        const ruleRows = rulesContainer.querySelectorAll('.rule-row');

        ruleRows.forEach(row => {
            const bot = row.children[0].value;
            const action = row.children[1].value;
            let path = row.children[2].value.trim();

            if (path) {
                // Ensure path starts with /
                if (!path.startsWith('/') && !path.startsWith('*')) {
                    path = '/' + path;
                }

                if (!customRules[bot]) {
                    customRules[bot] = [];
                }
                customRules[bot].push(`${action}: ${path}`);
            }
        });

        for (const bot in customRules) {
            // Avoid duplicating the * User-agent block if it contradicts the default,
            // but for simplicity in this generator, we just append it.
            txt += `User-agent: ${bot}\n`;
            customRules[bot].forEach(rule => {
                txt += `${rule}\n`;
            });
            txt += `\n`;
        }

        // 3. Sitemap
        const sitemap = sitemapInput.value.trim();
        if (sitemap) {
            txt += `Sitemap: ${sitemap}\n`;
        }

        txt += `\n# Generated by Project UT`;
        outputCode.textContent = txt.trim();
    }

    // Initial listeners
    defaultAccessSelect.addEventListener('change', generateRobotsTxt);
    sitemapInput.addEventListener('input', generateRobotsTxt);
    generateBtn.addEventListener('click', generateRobotsTxt);

    clearBtn.addEventListener('click', () => {
        defaultAccessSelect.value = 'allow';
        sitemapInput.value = '';
        rulesContainer.innerHTML = '';
        generateRobotsTxt();
    });

    copyBtn.addEventListener('click', () => {
        const textToCopy = outputCode.textContent;
        navigator.clipboard.writeText(textToCopy).then(() => {
            const originalText = copyBtn.textContent;
            copyBtn.textContent = 'Copied!';
            setTimeout(() => { copyBtn.textContent = originalText; }, 2000);
        });
    });

    downloadBtn.addEventListener('click', () => {
        const text = outputCode.textContent;
        const blob = new Blob([text], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);

        const a = document.createElement('a');
        a.href = url;
        a.download = 'robots.txt';
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    });

    // Add one empty rule row by default
    rulesContainer.appendChild(createRuleRow());
    generateRobotsTxt();
});